project:
  type: website

website:
  title: "Kaleb Fajardo Cervantes"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resume.qmd
      - projects.qmd
    right: 
      - icon: linkedin
        # text: LinkedIn
        href: https://www.linkedin.com/in/kfcervantes/
      - icon: github
        # text: GitHub
        href: https://github.com/KFCervantes

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



