---
title: "Induction Proofs"
format: html
description: "Explanation on how to do an induction proof"
---

One important thing to learn how to for a lot of theory based math courses is induction proofs. These have two steps:

1. The base case

    For this, we want to hold that the statement holds for some specific base case. This can vary depending on the problem.

2. The inductive step

    For this, we assume that the statement is true for some case, and then we show that the statement holds for the following case

If both the base case and inductive step hold, then the statement holds for the base case and all following cases.

## Variations
There is also a variation called "Strong Induction". This is very similar to regular induction, however the main difference is that we assume that the statement holds from the base case up to some specific case. This is a subtle difference, but may be important to use for some proofs.

## Example
Lets consider the following statement:

$\forall n \in \mathbb Z^+$

$$
\sum_{i = 1}^n i = \binom{n + 1}{2}
$$

Given this statement, we will want to look at the base case and inductive step.

### Base Case
In this case, $n$ can be any positive integer. The smallest possible value for $n$ is 1, so that is our base case.

First we simplify the left side of the equation.

$$
\sum_{i = 1}^1 i = 1
$$

Now we simplify the right side of the equation.

$$
\begin{aligned}
\binom{1 + 1}{2} &= \binom{2}{2} \\
&= 1
\end{aligned}
$$

Since both sides of the equation are equal to 1, the base case holds.

### Inductive step
For this, we assume that the statement is true for some $k \in \mathbb Z^+$. It may help to write this out with the formula.

$$
\sum_{i = 1}^k i = \binom{k + 1}{2}
$$

We want to show that the statement also holds for $k + 1$. This means proving

$$
\sum_{i = 1}^{k + 1} i = \binom{k + 2}{2}
$$

To do this, we will first rewrite the sum portion of the statement we want to prove.

$$
\sum_{i = 1}^{k + 1} i = \left( \sum_{i = 1}^{k} i\right) + (k + 1)
$$

Given our assumption for the inductive step, we can replace the sum with the binomial and do some algebraic stuff.

$$
\begin{aligned}
\sum_{i = 1}^{k + 1} i &= \left( \sum_{i = 1}^{k} i\right) + (k + 1) \\
&= \binom{k + 1}{2} + (k + 1) \\
&= \frac{(k + 1)_2}{2!} + (k + 1) \\
&= \frac{(k + 1) \cdot k}{2} + (k + 1) \\
&= (k + 1) \left( \frac{k}{2} + 1\right) \\
&= \frac{(k + 1) (k + 2)}{2} \\
&= \frac{(k + 2)_2}{2!} \\ 
&= \binom{k + 2}{2}
\end{aligned}
$$

This proved the inductive step. Now you may have noticed that this used a lot of algebra. This is sometimes the case.

### Implications for both holding
For this statement, the base case was true for $n = 1$. Since we also proved the induction step, we can let $k = 1$ and the statement will be true for $n = 2$. We can then repeat that induction step indefinatly. This means that for any $n \geq 2$, we can start at the base case and then repeat the induction step until we show the statement is true for $n$. This repeated induction step could take a while which is why we prove the step works. From there this process is implied.